### ISSUE TITLE
Encountered an error while working with Vyper-Server

### ISSUE THREAD

**Issue by Sahilsen** [jacqueswww/vyper-server#1]
Hi, when I perform ```pip install -r requirements.txt``` I'm getting the following error, can you suggest anything? 

![Screenshot (81)](https://user-images.githubusercontent.com/41318044/105783503-9ee0c680-5f9c-11eb-88c1-4d44171767ec.png)
![Screenshot (82)](https://user-images.githubusercontent.com/41318044/105783509-a1432080-5f9c-11eb-9eb8-c6540eadf2b1.png)

**Comment by jacqueswww** [comment]
This seems to be a related to python3.9; let me try with python3.9 and see if I can push a fix :)

**Comment by Sahilsen** [comment]
Thank you so much for getting back, yes I was trying it with pthon ver 3.9.1

**Comment by jacqueswww** [comment]
Just needed a version bump, check master branch and let  me know.

**Comment by Sahilsen** [comment]
Hi @jacqueswww so this time the server gets started, but it throws this while contract compilation

![Screenshot (85)](https://user-images.githubusercontent.com/41318044/106026073-643b7300-60ef-11eb-9ac8-1ad602aea059.png)

**Comment by Sahilsen** [comment]
any suggestions? @jacqueswww

**Comment by jacqueswww** [comment]
I updated the hosted remix compiler with the latest master yesterday, give that a shot maybe?

**Comment by Sahilsen** [comment]
Hey @jacqueswww, I just tried the remote compiler on Remix and it worked thank you so much for making things easier you rock.

**Comment by jacqueswww** [comment]
Sure no problem! If you need to run locally I am pretty confident the latest master version should get you going.
